INSERT INTO deporte (nombre) VALUES ("Clavados");
INSERT INTO deporte (nombre) VALUES ("Natación");
INSERT INTO deporte (nombre) VALUES ("Natación artística");
INSERT INTO deporte (nombre) VALUES ("Polo acuático");
INSERT INTO deporte (nombre) VALUES ("Natación en Aguas abiertas");
INSERT INTO deporte (nombre) VALUES ("Maratón");
INSERT INTO deporte (nombre) VALUES ("Marcha");
INSERT INTO deporte (nombre) VALUES ("Atletismo");
INSERT INTO deporte (nombre) VALUES ("Bádminton");
INSERT INTO deporte (nombre) VALUES ("Balonmano");
INSERT INTO deporte (nombre) VALUES ("Básquetbol");
INSERT INTO deporte (nombre) VALUES ("Básquetbol 3x3");
INSERT INTO deporte (nombre) VALUES ("Béisbol");
INSERT INTO deporte (nombre) VALUES ("Boxeo");
INSERT INTO deporte (nombre) VALUES ("Bowling");
INSERT INTO deporte (nombre) VALUES ("Breaking");
INSERT INTO deporte (nombre) VALUES ("Canotaje Slalom");
INSERT INTO deporte (nombre) VALUES ("Canotaje de velocidad");
INSERT INTO deporte (nombre) VALUES ("BMX Freestyle");
INSERT INTO deporte (nombre) VALUES ("BMX Racing");
INSERT INTO deporte (nombre) VALUES ("Mountain Bike");
INSERT INTO deporte (nombre) VALUES ("Ciclismo pista");
INSERT INTO deporte (nombre) VALUES ("Ciclismo ruta");
INSERT INTO deporte (nombre) VALUES ("Adiestramiento ecuestre");
INSERT INTO deporte (nombre) VALUES ("Evento completo ecuestre");
INSERT INTO deporte (nombre) VALUES ("Salto ecuestre");
INSERT INTO deporte (nombre) VALUES ("Escalada deportiva");
INSERT INTO deporte (nombre) VALUES ("Esgrima");
INSERT INTO deporte (nombre) VALUES ("Esquí acuático y Wakeboard");
INSERT INTO deporte (nombre) VALUES ("Fútbol");
INSERT INTO deporte (nombre) VALUES ("Gimnasia artística Masculina");
INSERT INTO deporte (nombre) VALUES ("Gimnasia artística Femenina");
INSERT INTO deporte (nombre) VALUES ("Gimnasia rítmica");
INSERT INTO deporte (nombre) VALUES ("Gimnasia trampolín");
INSERT INTO deporte (nombre) VALUES ("Golf");
INSERT INTO deporte (nombre) VALUES ("Hockey césped");
INSERT INTO deporte (nombre) VALUES ("Judo");
INSERT INTO deporte (nombre) VALUES ("Karate");
INSERT INTO deporte (nombre) VALUES ("Levantamiento de pesas");
INSERT INTO deporte (nombre) VALUES ("Lucha");
INSERT INTO deporte (nombre) VALUES ("Patinaje artístico");
INSERT INTO deporte (nombre) VALUES ("Skateboarding");
INSERT INTO deporte (nombre) VALUES ("Patinaje velocidad");
INSERT INTO deporte (nombre) VALUES ("Pelota vasca");
INSERT INTO deporte (nombre) VALUES ("Pentatlón moderno");
INSERT INTO deporte (nombre) VALUES ("Racquetball");
INSERT INTO deporte (nombre) VALUES ("Remo");
INSERT INTO deporte (nombre) VALUES ("Rugby 7");
INSERT INTO deporte (nombre) VALUES ("Sóftbol");
INSERT INTO deporte (nombre) VALUES ("Squash");
INSERT INTO deporte (nombre) VALUES ("Surf");
INSERT INTO deporte (nombre) VALUES ("Taekwondo");
INSERT INTO deporte (nombre) VALUES ("Tenis");
INSERT INTO deporte (nombre) VALUES ("Tenis de mesa");
INSERT INTO deporte (nombre) VALUES ("Tiro");
INSERT INTO deporte (nombre) VALUES ("Tiro con arco");
INSERT INTO deporte (nombre) VALUES ("Triatlón");
INSERT INTO deporte (nombre) VALUES ("Vela");
INSERT INTO deporte (nombre) VALUES ("Vóleibol");
INSERT INTO deporte (nombre) VALUES ("Vóleibol playa");
